### ISSUE TITLE
good luck, dont forget to use .gitignore from the beggining to prevent shit files from uploading to your project!

### ISSUE THREAD

**Issue by VictorRutskin** [Guy-S-glitch/my-pet-shop#1]

**Comment by VictorRutskin** [comment]
aka 
![image](https://github.com/Guy-S-glitch/my-pet-shop/assets/69360460/8230e312-f98f-4926-9832-6b8130f8a39d)

**Comment by VictorRutskin** [comment]
@Guy-S-glitch

**Comment by Guy-S-glitch** [comment]
i think i did it...
i dont see the node_module file
and i deleted the .vscode file on my side so it's not there anymore
but for some reason it's not doing it with every push

**Comment by VictorRutskin** [comment]
@Guy-S-glitch  great, just add README.md and you're done
